version: '3.8'
services:
  backend:
    build: ./back-end
    ports:
      - "8080:8080"
    volumes:
      # - ./server:/app
      - /app/node_modules
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb+srv://fatiha:fatiha12@cluster0.ugvhcfu.mongodb.net/youcode_overflow?retryWrites=true&w=majority
  frontend:
    build: ./client
    ports:
      - "3000:3000"
    volumes:
      - ./client/src:/app/src
  mongodb:
    image: mongo
    volumes:
      - mongodb-data:/data/db
volumes:
  mongodb-data:
    driver: local
